"git":
  "depth": !!bool >-
    false
"languge": >-
  nix
"matrix":
  "include":
  - "language": >-
      nix
    "name": >-
      cargo build & linters
    "nix": >-
      2.2.1
    "os": >-
      linux
    "script": >
      set -e

      source ./.travis_fold.sh

      travis_fold ci_check \
        nix-shell --quiet --run ci_check
      travis_fold travis-yml-gen \
        cat $(nix-build --quiet ./.travis.yml.nix --no-out-link) > .travis.yml
      travis_fold travis-yml-idempotent \
        git diff -q ./.travis.yml
  - "language": >-
      nix
    "name": >-
      cargo build & linters
    "nix": >-
      2.0
    "os": >-
      osx
    "script": >
      set -e

      source ./.travis_fold.sh

      travis_fold ci_check \
        nix-shell --quiet --run ci_check
      travis_fold travis-yml-gen \
        cat $(nix-build --quiet ./.travis.yml.nix --no-out-link) > .travis.yml
      travis_fold travis-yml-idempotent \
        git diff -q ./.travis.yml
  - "language": >-
      nix
    "name": >-
      nix-build
    "nix": >-
      2.2.1
    "os": >-
      linux
    "script": >
      set -e

      source ./.travis_fold.sh

      travis_fold lorri-nix-build \
        nix-build
      travis_fold lorri-install \
        nix-env -i ./result
      travis_fold lorri-self-upgrade \
        lorri self-upgrade local $(pwd)
  - "language": >-
      nix
    "name": >-
      nix-build
    "nix": >-
      2.0
    "os": >-
      osx
    "script": >
      set -e

      source ./.travis_fold.sh

      travis_fold lorri-nix-build \
        nix-build
      travis_fold lorri-install \
        nix-env -i ./result
      travis_fold lorri-self-upgrade \
        lorri self-upgrade local $(pwd)
